server:
  port: 7001
eureka:
  server:
    enable-self-preservation: false # 开发阶段false可以， 正式环境中建议启用自我保护模式
    eviction-interval-timer-in-ms: 1000 #踢出问题服务时间间隔60*1000ms
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，职责是维护实例，不参加检索
    service-url:
      defaultZone: http://localhost:7001/eureka/ #设置eureka server的交互地址，即对外暴露的地址
