server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml # mybatis配置文件所在路径
  type-aliases-package: com.itheima.hf.model # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/*.xml # mapper映射文件
spring:
  application:
    name: hf-itheima-cloud-provider # 重要(不能是下划线)
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?characterEncoding=utf-8
    # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间

eureka:
  instance:
    instance-id: hf-itheima-cloud-provider:8001 #修改别名
    prefer-ip-address: true #显示IP地址
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ #注册中心地址

#显示微服务信息
info:
  app.name: hf_itheima_cloud #父工程名称
  company.name: www.itheima.com  #域名
  build.artifactId: hf-itheima-cloud-provider #服务工程名
  build.version: 1.0 #版本号
  yyyy: 8888